name: csp_hasher
description: Dart CSP hash generator can hash your inline scripts and styles.
version: 1.0.0
homepage: https://jxstxn.dev
repository: https://github.com/jxstxn1/csp_hasher
issue_tracker: https://github.com/jxstxn1/csp_hasher/issues

environment:
  sdk: ^3.0.5

dependencies:
  crypto: ^3.0.3
  html: ^0.15.4

dev_dependencies:
  lint: ^2.0.0
  test: ^1.21.0
