name: csp_hasher
description: Dart CSP hash generator can hash your inline scripts and styles.
version: 1.0.1
homepage: https://jxstxn.dev
repository: https://github.com/jxstxn1/csp_hasher
issue_tracker: https://github.com/jxstxn1/csp_hasher/issues
topics:
  - dart
  - csp
  - hash
  - security
  - html

environment:
  sdk: ^3.0.0

dependencies:
  crypto: ^3.0.3
  html: ^0.15.4

dev_dependencies:
  lint: ^2.0.0
  test: ^1.21.0
